### ISSUE TITLE
Just curious how your solution compares to this one

### ISSUE THREAD

**Issue by ovizii** [elad-bar/ha-shinobi#1]
Hi there,

I've been using this one for a while https://github.com/xannor/ha_shinobicctv so I was wondering how your solution compares. 

Any notable differences you're aware off? I understand you might not have been of the other one in that case feel free to simply close my issue.

**Comment by elad-bar** [comment]
I didn't find an integration of Shinobi Video with configuration over UI,
That component includes motion and audio sensors over MQTT messages, I will contact the developer in order to merge my changes if he/she wants to

**Comment by ovizii** [comment]
I'm very happy someone else has tackled shinobi integration :-)
