### ISSUE TITLE
Motion sensor is being created although it's not enabled

### ISSUE THREAD

**Issue by ovizii** [elad-bar/ha-shinobi#10]
The description of this addon says:

> Description
> Integration with Shinobi Video NVR. Creates the following components:
> 
> Camera - per-camera defined.
> Binary Sensors (MOTION, SOUND) - per-camera defined.

The result of adding 1 shinobi camera with your addon:
![image](https://user-images.githubusercontent.com/837902/120936436-099ecd00-c708-11eb-9434-e2e96aa319f1.png)

**Comment by elad-bar** [comment]
Not sure I understand, what is the issue?

**Comment by ovizii** [comment]
Not sure if I am misunderstanding something but should your addon not create a binary sensor for Sound for this camera? As you can see it only created 1 binary sensor for Motion.

**Comment by ovizii** [comment]
Does this mean somehow the sound from the shinobi camera isn't picked up?

![image](https://user-images.githubusercontent.com/837902/121039875-c0a35300-c7b1-11eb-93c1-3e2e897c588b.png)

**Comment by elad-bar** [comment]
Binary sensor of audio is dependent on sound detector, please enable it to have that binary sensor

**Comment by ovizii** [comment]
yes, motion detection is indeed turned off in shinobi but so is motion detection and that binary sensor gets created, hence my confusion.

I'll share some relevant shinobi settings:

![image](https://user-images.githubusercontent.com/837902/121216229-febb7800-c880-11eb-96fa-865e32f377ec.png)

![image](https://user-images.githubusercontent.com/837902/121216283-0bd86700-c881-11eb-9390-8fe72b9fb04e.png)

![image](https://user-images.githubusercontent.com/837902/121216328-1692fc00-c881-11eb-8fac-f1d183a9c3e0.png)

![image](https://user-images.githubusercontent.com/837902/121216381-201c6400-c881-11eb-818e-3f90c2eb0041.png)

![image](https://user-images.githubusercontent.com/837902/121216447-2dd1e980-c881-11eb-9011-5fdb764bf8d7.png)

**Comment by ovizii** [comment]
> Does this mean somehow the sound from the shinobi camera isn't picked up?
> 
> ![image](https://user-images.githubusercontent.com/837902/121039875-c0a35300-c7b1-11eb-93c1-3e2e897c588b.png)

Does this really mean, HA is not picking up any sound via this camera? 
I tried changing the stream settings in shinobi from "Audio Codec: copy" to a few other codecs and HA is still not seeing any audio. 

Any hints?

![image](https://user-images.githubusercontent.com/837902/121216713-75587580-c881-11eb-8664-f4340afa04aa.png)

**Comment by elad-bar** [comment]
Will recheck it during the weekend, thanks for the details

**Comment by ovizii** [comment]
> Will recheck it during the weekend, thanks for the details

Sure, may thanks for your help, especially since I don't think its related to your addon but more like a wrong setting on shinobi side.

**Comment by elad-bar** [comment]
Can you please export the camera setting (json) and share it (after cleanup of ip and credentials)?

Thanks

**Comment by ovizii** [comment]
Should be clean of any passwords. Just remove the .txt at the end.
[Shinobi_doggyCam_config.json.txt](https://github.com/elad-bar/ha-shinobi/files/6629787/Shinobi_doggyCam_config.json.txt)

**Comment by elad-bar** [comment]
thanks for the config file, 
regarding motion sensor, code was referring to the wrong parameter of detector for motion detector - it should be detector_pam,
As for the audio detector, according to the config and the screenshot the audio detector is turned off, in order to enabled it, please enable it, reload the component / restart HA and let me know if it works for you

thanks

**Comment by ovizii** [comment]
I don't need the motion detector, I was just wondering why motion detector sensor was there but not audio detector sensor since both were turned off in shinobi. 

so basically, once you update your integration, when I add the camera again, none of the 2 sensors should be created since both detection methods are off in shinobi, right?

**Comment by elad-bar** [comment]
That's the plan 😀,  just wanted to make sure that I don't need to check the audio sensor,
Thanks
