### ISSUE TITLE
Audio on stream

### ISSUE THREAD

**Issue by arag00rn** [elad-bar/ha-shinobi#11]
Hi guys,

I'm wondering if there is anyway to get audio streaming directly on HA.

Audio is working fine on Shinobi UI. I tried with both codecs: aac / mp3. No audio.
I tried with different browser Brave/Chrome/Safari

Do you know if it's possible or have any suggestion?

Thank you!

**Comment by elad-bar** [comment]
It seems like an issue with the stream component of HA, I also get the audio for 2 of 10 camera with audio

**Comment by elad-bar** [comment]
found a thread about it:
https://github.com/home-assistant/core/issues/47084

**Comment by elad-bar** [comment]
Since this issue is related to stream component, I close that issue
