### ISSUE TITLE
Special characters in password

### ISSUE THREAD

**Issue by ecarjat** [elad-bar/ha-shinobi#12]
Thanks for doing this. As an FYI having an '@' in the password prevents the login from working.

**Comment by elad-bar** [comment]
Can you please send the logs in debug log level?

Thanks

**Comment by elad-bar** [comment]
checked it, it accepts special characters in password field, please provide debug log level so i'll be able to assist

thanks

**Comment by ecarjat** [comment]
Thanks for the super fast reply. I’ll provide a log shortly.

**Comment by elad-bar** [comment]
Any updates?
