### ISSUE TITLE
Various issues with creating the integration

### ISSUE THREAD

**Issue by SnakeZZZ** [elad-bar/ha-shinobi#13]
Hello,

I'm trying to use the integration on a freshly installed shinobi. 
Shinobi itself seems to work fine with my one camera, but I can't seem to get the integration in HA to work.

First of all: What is supposed to go into the "Path" configuration (I left it empty)?
Second: I cannot seem to find the logging options settings in the integration

Once I've created the integration, I get a couple of errors:

```
This error originated from a custom integration.

Logger: custom_components.shinobi.api.shinobi_api
Source: custom_components/shinobi/api/shinobi_api.py:213
Integration: Shinobi Video NVR (documentation, issues)
First occurred: 16:12:01 (11 occurrences)
Last logged: 16:16:33

Failed to get permanent API Key, please go to Shinobi Video Dashboard and add API for `my@mailadre.ss`
```

I have - however - created the API key for the user my@mailadre.ss in Shinobi (0.0.0.0 and everything else set to "yes")

Also, this one:
```
This error originated from a custom integration.

Logger: custom_components.shinobi.managers.home_assistant
Source: custom_components/shinobi/managers/home_assistant.py:257
Integration: Shinobi Video NVR (documentation, issues)
First occurred: 16:11:38 (6 occurrences)
Last logged: 16:20:30

Failed to async_update, Error: 'str' object has no attribute 'get', Line: 247
```

What am I doing wrong?

Regards,
SnakezZZ

**Comment by elad-bar** [comment]
Is it still relevant?

**Comment by RobHofmann** [comment]
I'm still getting the following error.
```
2021-08-16 12:15:03 ERROR (MainThread) [custom_components.shinobi.managers.home_assistant] Failed to async_update, Error: 'str' object has no attribute 'get', Line: 247
```

**Comment by elad-bar** [comment]
Can you please share a debug level log to better understand the issue?

Thanks

**Comment by elad-bar** [comment]
@SnakeZZZ is it still relevant?

thanks

**Comment by elad-bar** [comment]
Closing the issue, if still relevant, please reopen
