### ISSUE TITLE
Missing Binary Motion Sensors

### ISSUE THREAD

**Issue by j007bond007** [elad-bar/ha-shinobi#15]
Hello, I've had this plugin for a while but just started to seriously try and utilize it. I did a bunch of updates to HA and this plugin and configured my cameras in Shinobi to have different motion/quality settings and noticed that my binary sensors became invalid, and upon removing them and even removing the plugin and re-installing it I only see 2 entities and 2 devices (my actual 2 camera feeds). 

What happened to the binary sensor for when there is motion? How can I get something to trigger an automation rule when Tensorflow detects a person in Shinobi? Thanks!

**Comment by elad-bar** [comment]
Binary sensor for motion will be created only if Shinobi Video Server configuration (per monitor) is enabled,
If you are activating the object detection plugin, you should receive the evnt as described in README

**Comment by j007bond007** [comment]
Thanks for your reply. Video Server Configuration? Is that the name of the setting as I'm not seeing that in the monitor settings?

**Comment by elad-bar** [comment]
Is the motion detection enabled in Shinobi Video server (application)?

**Comment by j007bond007** [comment]
I have Tensorflow setup on the Shinobi server and it shows as PRIMARY ENGINE : TENSORFLOW CONNECTED inside of both of my monitors. I have it setup so the built-in basic motion sensor is disabled but Tensorflow "Object Detection" is enabled - and I can see the coloured square around people.

**Comment by j007bond007** [comment]
![image](https://user-images.githubusercontent.com/85252952/131548352-435cc976-be55-4a2f-9b21-41124cb78907.png)
![image](https://user-images.githubusercontent.com/85252952/131548402-4545685d-4ad2-4dd2-8384-8005a3a5008a.png)
![image](https://user-images.githubusercontent.com/85252952/131548438-add3e3cc-b70a-4b09-8a3f-a2b8b1d254cf.png)

**Comment by elad-bar** [comment]
Great, that means that it should create the binary sensor, if it doesn't, can you please export the monitor json (by clicking on the options -> export) and post it (after cleaning credentials from the json)

Thanks

**Comment by j007bond007** [comment]
[Shinobi_3a4jn88LRc8000_config.txt](https://github.com/elad-bar/ha-shinobi/files/7085771/Shinobi_3a4jn88LRc8000_config.txt)
Here you go - renamed to .txt as it wouldn't let me upload - no binary sensor still.

**Comment by elad-bar** [comment]
Will check it tomorrow, from a snap review of your config, it seems you have defined rules (confidence and object), can you please clone the monitor without those rules to check if it's being reported to ha?

**Comment by j007bond007** [comment]
The monitor's video feed gets reported but still no binary sensor entity
