### ISSUE TITLE
[FR] Switch to enable/disable motion detection

### ISSUE THREAD

**Issue by chemelli74** [elad-bar/ha-shinobi#22]
Would be nice to have a switch to enable/disable motion detection.

Thx for considering,

Simone

**Comment by chemelli74** [comment]
Just found the time to update and test; seems the switch is not created on my instance.
Should I do something special ?

Simone

**Comment by elad-bar** [comment]
Please use the service to disable / enable the motion detection:
`camera.disable_motion_detection`
`camera.enable_motion_detection`

Wwitch for camera is when you would like to turn it off (e.g. stop recording) - didn't implement it yet.

reason for not having it as switch (other than the fact in none of the integration there is switch for that):
I find it as an overkill as I have 17 camera, meaning 17 additional components,
but... if you would like to create a template switch feel free to do so.

hope it makes sense :)

**Comment by chemelli74** [comment]
Hi @elad-bar, thx for the explanation.

Basically what is missing is a visual status of the motion (on/off).
Other core integrations, like MotionEye have it: <https://github.com/home-assistant/core/blob/dev/homeassistant/components/motioneye/switch.py#L29-L34>

Take also care that HA is not suggesting the usage of a service when there are no parameters to call it, but instead is pushing for button entities.

Simone

**Comment by elad-bar** [comment]
The functionality of the service as I suggested is written by HA, I just implemented the function was already there.

Just to understand better the need, can you pls share the scenario you would like to use that kind of switch?

**Comment by chemelli74** [comment]
Basically I would like to know the status of the motion detection plus an UI way to easily toggle it.
This is why the `switch` entity suits perfectly imho.

If you don't want to have them on by default, there are 2 ways:

- create them disabled
- add a option under configure to avoid creation

If you want to discuss further, you find me on [Discord](https://discord.com/invite/home-assistant): `chemelli74#2180`

Thx,

Simone

**Comment by elad-bar** [comment]
just for you :)

## 1.2.2

- Add support to control monitor motion / sound detection using switch per monitor
  - Toggle off detector (motion / sound) will remove the entity
  - Toggle on will restore the entity
  - Switch for sound detection will not be available if monitor has no audio channel
  - Any action will be logged with response from Shinobi Video Server

- Unique ID is now being calculated automatically based on the entity's domain and name
- Improved camera component creation
  - Reduced the data of camera component
  - Reduced the amount of updates for camera component

**Comment by chemelli74** [comment]
WoW, thx so much mate !!!

Really really appreciated!

Simone
