### ISSUE TITLE
what configuration needed for motion event to work?

### ISSUE THREAD

**Issue by sacy80** [elad-bar/ha-shinobi#25]
Hi would like to know what configuration are need on shinobi to configure to work with the ha-shinobi plugin? im able to get video feed abut motion detection always are "clear".

**Comment by elad-bar** [comment]
In readme there is a link to documentation of Shinobi Motion Detection,  please follow it up and let me know if it works for you

**Comment by sacy80** [comment]
Hi. i have follow the doc from shinobi Motion Detection. it work on shinobi end.  but when there motion, it didnt register in HA

this are the config info from my shinobi.

{"mode":"record","mid":"aihIjZTTrS","name":"Tapo-C210","type":"h264","protocol":"rtsp","host":"XX.XX.XX.XX","port":"554","path":"/stream1","height":"480","width":"640","ext":"mp4","fps":"1","details":{"max_keep_days":"7","notes":"","dir":"","rtmp_key":"","auto_host_enable":"1","auto_host":"rtsp://XX.XX.XX.XX:554/stream1","rtsp_transport":"tcp","muser":"username","mpass":"password","port_force":"0","fatal_max":"0","skip_ping":null,"is_onvif":"1","onvif_non_standard":"0","onvif_port":"2020","primary_input":"0:0","aduration":"1000000","probesize":"1000000","stream_loop":"0","sfps":"","wall_clock_timestamp_ignore":"1","accelerator":"0","hwaccel":"auto","hwaccel_vcodec":"","hwaccel_device":"","stream_type":"hls","stream_flv_type":"ws","stream_flv_maxLatency":"","stream_mjpeg_clients":"","stream_vcodec":"copy","stream_acodec":"no","hls_time":"2","hls_list_size":"3","preset_stream":"ultrafast","stream_quality":"15","stream_fps":"","stream_scale_x":"","stream_scale_y":"","stream_rotate":null,"signal_check":"10","signal_check_log":"0","stream_vf":"","tv_channel":"0","tv_channel_id":"","tv_channel_group_title":"","stream_timestamp":"0","stream_timestamp_font":"","stream_timestamp_font_size":"","stream_timestamp_color":"","stream_timestamp_box_color":"","stream_timestamp_x":"","stream_timestamp_y":"","stream_watermark":"0","stream_watermark_location":"","stream_watermark_position":"tr","snap":"1","snap_fps":"","snap_scale_x":"","snap_scale_y":"","snap_vf":"","vcodec":"copy","crf":"1","preset_record":"","acodec":"no","record_scale_y":"","record_scale_x":"","cutoff":"15","rotate":null,"vf":"","timestamp":"0","timestamp_font":"","timestamp_font_size":"10","timestamp_color":"white","timestamp_box_color":"0x00000000@1","timestamp_x":"(w-tw)/2","timestamp_y":"0","watermark":"0","watermark_location":"","watermark_position":"tr","record_timelapse":null,"record_timelapse_mp4":null,"record_timelapse_fps":null,"record_timelapse_scale_x":"","record_timelapse_scale_y":"","record_timelapse_vf":"","record_timelapse_watermark":null,"record_timelapse_watermark_location":"","record_timelapse_watermark_position":null,"cust_input":"","cust_stream":"","cust_snap":"","cust_record":"","cust_detect":"","cust_detect_object":"","cust_sip_record":"","custom_output":"","detector":"1","detector_http_api":null,"detector_send_frames":"1","detector_fps":"","detector_scale_x":"640","detector_scale_y":"480","detector_lock_timeout":"","detector_save":"1","detector_record_method":"sip","detector_trigger":"1","detector_trigger_record_fps":"","detector_timeout":"2","detector_send_video_length":"","watchdog_reset":"0","detector_delete_motionless_videos":"0","det_multi_trig":null,"group_detector_multi":"","detector_webhook":"0","detector_webhook_timeout":"","detector_webhook_url":"","detector_webhook_method":null,"detector_command_enable":"0","detector_command":"","detector_command_timeout":"","snap_seconds_inward":"","detector_mail":"0","detector_mail_timeout":"","use_detector_filters":null,"use_detector_filters_object":null,"cords":"{\"3N10M\":{\"name\":\"Foyer\",\"sensitivity\":10,\"max_sensitivity\":\"\",\"threshold\":1,\"color_threshold\":9,\"points\":[[\"2\",\"90\"],[\"3\",\"263\"],[\"1\",\"305\"],[\"4\",\"477\"],[\"241\",\"479\"],[\"636\",\"479\"],[\"637\",\"327\"],[\"638\",\"145\"],[\"518\",\"144\"],[\"319\",\"142\"],[\"322\",\"280\"],[\"258\",\"267\"],[\"219\",\"261\"],[\"214\",\"195\"],[\"187\",\"131\"],[\"136\",\"86\"],[\"75\",\"88\"]]}}","detector_filters":"","detector_pam":"1","detector_sensitivity":"","detector_max_sensitivity":"","detector_threshold":"1","detector_color_threshold":"","inverse_trigger":null,"detector_frame":"0","detector_noise_filter":"1","detector_noise_filter_range":"","detector_notrigger":"1","detector_notrigger_mail":"0","detector_notrigger_discord":null,"detector_notrigger_timeout":"","detector_notrigger_webhook":null,"detector_notrigger_webhook_url":"","detector_notrigger_webhook_method":null,"detector_notrigger_command_enable":null,"detector_notrigger_command":"","detector_notrigger_command_timeout":"","detector_audio":null,"detector_audio_min_db":"","detector_audio_max_db":"","detector_use_detect_object":"0","detector_send_frames_object":"0","detector_obj_count_in_region":null,"detector_obj_region":null,"detector_use_motion":"1","detector_fps_object":"","detector_scale_x_object":"","detector_scale_y_object":"","detector_lisence_plate":"0","detector_lisence_plate_country":"us","detector_buffer_vcodec":"copy","detector_buffer_acodec":"no","detector_buffer_fps":"","event_record_scale_x":"","event_record_scale_y":"","detector_buffer_hls_time":"","detector_buffer_hls_list_size":"","detector_buffer_start_number":"","detector_buffer_live_start_index":"","control":"1","control_base_url":"","control_url_method":"ONVIF","control_digest_auth":null,"control_stop":"1","control_url_stop_timeout":"","control_turn_speed":"","detector_ptz_follow":null,"detector_ptz_follow_target":"","detector_obj_count":"1","control_url_center":"","control_url_left":"","control_url_left_stop":"","control_url_right":"","control_url_right_stop":"","control_url_up":"","control_url_up_stop":"","control_url_down":"","control_url_down_stop":"","control_url_enable_nv":"","control_url_disable_nv":"","control_url_zoom_out":"","control_url_zoom_out_stop":"","control_url_zoom_in":"","control_url_zoom_in_stop":"","control_invert_y":null,"groups":"[]","notify_email":null,"notify_onUnexpectedExit":null,"notify_useRawSnapshot":null,"loglevel":"warning","sqllog":"0","detector_cascades":"","stream_channels":"","input_maps":"","input_map_choices":""},"shto":"[]","shfr":"[]"}

thanks alot for the help :)

**Comment by elad-bar** [comment]
According to the monitor configuration from Shinobi Video it seems that detector is on, but there are detector filter set for that monitor.

Do you get motion alerts within Shinobi Video UI?
If you do - please set the log level of the component within HA to debug, zip it and upload so I'll be able to debug it,
If you don't see motion alerts within Shinobi Video - I suggest to post over Shinobi Discord Help channel to find a solution.

thanks

**Comment by elad-bar** [comment]
issue is opened for long time without an update, closing it, if needed, please reopen and post more details,
thanks
