### ISSUE TITLE
Media Browser unknown error

### ISSUE THREAD

**Issue by kvtong93** [elad-bar/ha-shinobi#26]
Hi Guys,

i have experienced an unkown error when i enter  media browser.
<img width="270" alt="CleanShot 2022-07-01 at 17 25 48@2x" src="https://user-images.githubusercontent.com/56487514/176867095-3f5318ba-4b81-4c1e-94d5-0d6af49002da.png">

**Comment by elad-bar** [comment]
Can you pls provide more details? Logs? 

Thanks

**Comment by kvtong93** [comment]
Thanks bro, i restarted the hass.. It's ok ok now..

发自我的iPhone
