### ISSUE TITLE
No camera entinty added.

### ISSUE THREAD

**Issue by apoorv569** [elad-bar/ha-shinobi#27]
I installed this plugin today and connected to my `Shinobi` instance, it connected successfully but I don't get a camera entity or any video stream of any sort only binary sensors and switches.

![2022-07-14_16-30](https://user-images.githubusercontent.com/53279454/178968822-5b898358-08db-43a2-8513-89e89be6f86b.png)
![2022-07-14_16-31](https://user-images.githubusercontent.com/53279454/178968831-22d5ea69-9c0c-4f36-a341-f09e26b41302.png)

**Comment by elad-bar** [comment]
Pls post logs to understand the issue

Thanks

**Comment by apoorv569** [comment]
> Pls post logs to understand the issue
> 
> Thanks

Sure, Where can I find the logs?

**Comment by elad-bar** [comment]
Instructions for troubleshooting is in the readme (main page), logs are the home assistant logs (integration logs will be available once you will set the configuration according to the instructions)

**Comment by apoorv569** [comment]
> Instructions for troubleshooting is in the readme (main page), logs are the home assistant logs (integration logs will be available once you will set the configuration according to the instructions)

My bad, I forgot to enable the `JPEG API` the camera shows up now.

Closing this now.

**Comment by elad-bar** [comment]
Np, happy to see it works for you now
