### ISSUE TITLE
Failed to async_update, Error: replace() argument 2 must be str, not None, Line: 208

### ISSUE THREAD

**Issue by CarsonF** [elad-bar/ha-shinobi#3]
I was able to get the integration connected but on HA restart I got this and login failed (shinobi_api.py:209). 

Thanks a bunch for this. Hoping shinobi works out better than zoneminder. Would love to get deepstack integrated as well, so excited that you are handling this as well!

**Comment by CarsonF** [comment]
Figured out that login is looking for an API key to exist and fails if one hasn't been manually created. Maybe it'd just be easier to ask for that directly instead of login creds?

**Comment by elad-bar** [comment]
I will add it to the readme and add clearer error message, thanks
