### ISSUE TITLE
problem with initial config form

### ISSUE THREAD

**Issue by couardcourageux** [elad-bar/ha-shinobi#30]
Hi, 
![image](https://user-images.githubusercontent.com/28952445/180649520-4362ae84-85dc-48d1-afdf-58e298571700.png)
i have this PATH field, but i do not find it in your documentation. Furthermore, at First i had so much errors, now, it loads for 30 minutes, and then nothing. in path, i put /<api key> . So i really don't know
Thanks for the work on this integration by the way, it seems to work for many.
Have a good day

**Comment by gniknalu** [comment]
Same.

**Comment by elad-bar** [comment]
Added the missing parameter to documentation, please let me know if it address the issue

| Fields name | Type      | Required | Default   | Description                                                             |
|-------------|-----------|----------|-----------|-------------------------------------------------------------------------|
| Host        | Texbox    | +        | None      | Hostname or IP address of the Shinobi Video server                      |
| Port        | Textbox   | +        | 0         | HTTP Port to access Shinobi Video server                                |
| Path        | Textbox   | -        | Empty     | If Shinobi Video Server NVR has non default path, please adjust it here |
| SSL         | Check-box | +        | Unchecked | Is SSL supported?                                                       |
| Username    | Textbox   | -        |           | Username of dashboard user for Shinobi Video server                     |
| Password    | Textbox   | -        |           | Password of dashboard user for Shinobi Video server                     |

**Comment by couardcourageux** [comment]
yes, it adresses it, thank you
