### ISSUE TITLE
On initial Home Assistant start the "original stream" is loaded. After reloading the integration the Shinobi stream is used.

### ISSUE THREAD

**Issue by tr1plus** [elad-bar/ha-shinobi#31]
**Issue explained**

1. Start Home Assistant
2. Preview the video stream entities in Home Assistant and validate they are not the same as the streams show in Shinobi (assumption these are the "original streams" from the cameras)
3. Go to Integrations and reload the Shinobi integration
4. Preview the video stream entities in Home Assistant and validate they are now showing the same stream is in Shinobi

**Assumption**
My current assumption (and I didn't dive in code yet) - is that on original load of the Shinobi integration, the "use original stream" checkbox is checked by default.

After a reload of the integration, the checkbox is correct checked with the configuration and the correct streams load.

**Expected behaviour**
The correct streams get loaded on initial boot of Home Assistant

Thanks!

**Comment by elad-bar** [comment]
Original stream = Stream from the camera

Added to readme details about it:
![image](https://user-images.githubusercontent.com/3207137/194694882-54cd20fc-39be-4d58-9fcd-96dff4a9a2f8.png)

**Comment by mtgpcs** [comment]
I know this is closed, but where is this toggle located?

**Comment by elad-bar** [comment]
Under the device of server
