### ISSUE TITLE
camera entity not capturing any frames

### ISSUE THREAD

**Issue by ronluna** [elad-bar/ha-shinobi#37]
For some reason the logs shows the following during startup:

`
This error originated from a custom integration.

Logger: custom_components.shinobi.core.components.camera
Source: custom_components/shinobi/core/components/camera.py:166
Integration: Shinobi Video NVR (documentation, issues)
First occurred: 10:51:21 AM (2 occurrences)
Last logged: 10:51:21 AM

Failed to initialize CoreCamera instance, Error: invalid literal for int() with base 10: '', Line: 63
`

And I assume this is the reason why the card on the dashboard does not display any video feed and the logs shows the following when trying to access the shinobi card in the dashboard:

`
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/shinobi/core/components/camera.py:119
Integration: Shinobi Video NVR (documentation, issues)
First occurred: 10:53:36 AM (3 occurrences)
Last logged: 10:53:38 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 722, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 740, in handle
    image = await _async_get_image(
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 169, in _async_get_image
    if image_bytes := await camera.async_camera_image(
  File "/config/custom_components/shinobi/core/components/camera.py", line 119, in async_camera_image
    url = self._still_image_url.async_render()
AttributeError: 'NoneType' object has no attribute 'async_render'

`

Everything works as expected except the camera feeds (Motion detection works.. etc...)...

Any ideas how to solve this?

**Comment by elad-bar** [comment]
can you please check latest version (v2.0.12)?

thanks

**Comment by ronluna** [comment]
All working correctly now after upgrading.
Thanks!!!

By the way, wondering if there is anyway to sideload shinobi into Home assistant so recorded events can bee easily access ?

**Comment by elad-bar** [comment]
Recordings are available in media browser, is that what you are looking for?

**Comment by ronluna** [comment]
I was trying to see if there is a way to access shinobi's recording from within HA without having to leave the HA UI. would media browser allows to access recording from within HA? I'm trying to find it but I can't seem to see it anywhere..

Apologies for the late reply, I've been away for the past few days... 

Amazing plugin... Thanks!

**Comment by elad-bar** [comment]
That's ok, and thanks for the feedback.

Yes, it should provide you the ability to see videos from recording,
Did you set the media browser integration? If you did, you should see the recording folder in it,
If it's not working, please let me know

Thanks

**Comment by ronluna** [comment]
Found the "Media Browser" never used it before.  Recordings are in there! 

Thumbnails for each recording are not showing. is it normal?

![image](https://user-images.githubusercontent.com/9822111/199753642-d04924fe-c71a-4f23-aff1-52f7c0217d09.png)

**Comment by elad-bar** [comment]
Mainly because Shinobi doesn't produce them and didn't want to extract it from video on runtime (to avoid overloading the HA)

**Comment by elad-bar** [comment]
I will try to see if I can create a plugin for Shinobi that produces it once video file is created and then use it

**Comment by ronluna** [comment]
Sweet!!!

**Comment by elad-bar** [comment]
@ronluna thumbnails support add

## 2.0.18

Major refactor for the media source component:
- Browsing now support up to 7 days of videos per camera
- Navigation model changed - Shinobi Camera -> Camera -> Day -> List of all videos from that day
- Thumbnails support added (requires Shinobi Thumbnail customAutoLoad script, more details in README)
- Performance improvement Loading the videos is now on demand and not every update of the integration (every 60 seconds)

**Thumbnails support**

Shinobi Video does not provide out of the box thumbnails endpoint, to add that support, please follow the instructions in [shinobi-thumbnails](https://gitlab.com/elad.bar/shinobi-thumbnails) repository.

**Comment by ronluna** [comment]
Testing now. Although it seems the is installed and enabled it does not seems to be working.

![image](https://user-images.githubusercontent.com/9822111/200694136-40fe727e-0d5d-4c5e-b78b-e342d7f51de4.png)

`curl http://10.10.10.180:8080/:removed/thumbnails/:ke
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /:removed/thumbnails/:ke</pre>
</body>
</html>
`
Also Home assistant is no longer able to play shinobi's recordings from the media browser. It does show a thumbnail of the cameras and the day but once inside a day it won't show the thumbnail and it won't play any video when clicking on them.

**Comment by elad-bar** [comment]
Please open another issue for the media playing that does not work.

As for the shinobi, it seems that you have installed it as plugin and not as a customAutoLoad,
If you installed it as customAutiLoad, please report in the shinobi-thumbnails repo (gitlab)

Thanks

**Comment by elad-bar** [comment]
found the issue with the media play for media source, v2.0.19 solves it

**Comment by elad-bar** [comment]
also updated documentation for shinobi-thumbnails in its repository (GitLab)

## How to install

Get latest release from GitLab:

- Open `shinobi-thumbnails` [releases](https://gitlab.com/elad.bar/shinobi-thumbnails/-/releases)
- Copy the link of `Source code (zip)` asset of latest version

Install Shinobi customAutoLoad:

- Login to the super dashboard
- Open tab `Custom Auto Load`
- Paste the release asset ZIP file url in the `Download URL for Module`
- Click on `Download`
- In the package added to the list, click on `Enable`
- Restart Shinobi Video

*If previous version of the module is installed, remove it before updateing*
