### ISSUE TITLE
Integration broken

### ISSUE THREAD

**Issue by dougroutledge** [elad-bar/ha-shinobi#38]
The latest update broke the integration, removing, and attempting to re-add results in Config flow could not be loaded: {"message":"Invalid handler specified"}

**Comment by dougroutledge** [comment]
Logger: homeassistant.setup
Source: setup.py:192
First occurred: 7:47:55 AM (1 occurrences)
Last logged: 7:47:55 AM

Setup failed for custom integration shinobi: Unable to import component: cannot import name 'MonitorNotFoundError' from 'custom_components.shinobi.component.helpers.exceptions' (/config/custom_components/shinobi/component/helpers/exceptions.py)

**Comment by elad-bar** [comment]
thanks, will release new version later today with the fix for it

**Comment by elad-bar** [comment]
can you please confirm that it works for you with latest version?

thanks
