### ISSUE TITLE
Media browser using camera identifier. Possible to use camera name instead?

### ISSUE THREAD

**Issue by ronluna** [elad-bar/ha-shinobi#46]
Would it possible to use the name of the camera instead of the identifier when accessing recordings from within Home assistant media browser ?

<img width="568" alt="image" src="https://user-images.githubusercontent.com/9822111/227716195-07de99f8-b9a8-4791-9364-2a0ed98f5c84.png">

**Comment by elad-bar** [comment]
fixed in v3.0.1, pls check and update

thanks

**Comment by elad-bar** [comment]
@ronluna any updates?

Thanks

**Comment by elad-bar** [comment]
Closing the issue due to lack of activity

**Comment by ronluna** [comment]
Working great!

Thanks!!!
