### ISSUE TITLE
Motion detection stopped working since 3.x

### ISSUE THREAD

**Issue by skvalex** [elad-bar/ha-shinobi#49]
HA doesn't detect motion events.

Just checked the previous version (v2.0.34), it works fine there. Updated again to 3.0.1 - stopped working. Shinobi server hasn't changed during the test.

Here's the log, but there's nothing interesting there unfortunately. Debug logging is enabled.

<details><summary>The log</summary>home-assistant  | 2023-08-01 00:43:49.354 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
home-assistant  | 2023-08-01 00:43:50.025 DEBUG (MainThread) [custom_components.shinobi.managers.websockets] Sending message, Data: 42["pong", {"beat": 1}], Status: Connected to the API
home-assistant  | 2023-08-01 00:43:50.354 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
home-assistant  | 2023-08-01 00:43:51.005 DEBUG (MainThread) [custom_components.shinobi.managers.websockets] Payload (42) received, Type: diskUsed
home-assistant  | 2023-08-01 00:43:51.038 DEBUG (MainThread) [custom_components.shinobi.managers.websockets] Payload (42) received, Type: diskUsed
home-assistant  | 2023-08-01 00:43:51.354 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
home-assistant  | 2023-08-01 00:43:52.354 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
home-assistant  | 2023-08-01 00:43:53.353 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
home-assistant  | 2023-08-01 00:43:54.355 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
home-assistant  | 2023-08-01 00:43:55.019 DEBUG (MainThread) [custom_components.shinobi.managers.websockets] Payload (42) received, Type: os
home-assistant  | 2023-08-01 00:43:55.353 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
home-assistant  | 2023-08-01 00:43:56.355 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
home-assistant  | 2023-08-01 00:43:57.355 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
home-assistant  | 2023-08-01 00:43:58.025 DEBUG (MainThread) [custom_components.shinobi.managers.websockets] Sending message, Data: 42["pong", {"beat": 1}], Status: Connected to the API
home-assistant  | 2023-08-01 00:43:58.354 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
home-assistant  | 2023-08-01 00:43:59.354 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
home-assistant  | 2023-08-01 00:44:00.354 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
home-assistant  | 2023-08-01 00:44:01.355 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
home-assistant  | 2023-08-01 00:44:02.353 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
home-assistant  | 2023-08-01 00:44:03.355 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
home-assistant  | 2023-08-01 00:44:04.353 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
home-assistant  | 2023-08-01 00:44:05.018 DEBUG (MainThread) [custom_components.shinobi.managers.websockets] Payload (42) received, Type: os
home-assistant  | 2023-08-01 00:44:05.354 DEBUG (MainThread) [custom_components.shinobi.managers.coordinator] Finished fetching Shinobi Video data in 0.000 seconds (success: True)
</details>

HA version: Home Assistant 2023.7.3
Shinobi version: the latest dev branch with changes from [this](https://gitlab.com/Shinobi-Systems/Shinobi/-/merge_requests/475) MR running in docker

**Comment by elad-bar** [comment]
I can confirm that it's not working for me as well, will check it over the weekend

Thanks

**Comment by elad-bar** [comment]
pls check with latest [v3.0.2](https://github.com/elad-bar/ha-shinobi/releases/tag/v3.0.2)

thanks

**Comment by skvalex** [comment]
@elad-bar it works fine now, thanks!
