### ISSUE TITLE
Invalid server details

### ISSUE THREAD

**Issue by SHHA24** [elad-bar/ha-shinobi#5]
Hi 
running core-2021.5.5 on Debian + Docker
have Shinobi running and all working standalone, trying to login at the initial setup integration keeps saying  "Invalid server details"
Its the same details i use to access the shinobi server dashboard? 

does it only work on the Shinobi Pro? 

thanks

**Comment by elad-bar** [comment]
can you please share logs?

thanks

**Comment by juan11perez** [comment]
good day. First thank you for producing this.
Same problem

`2021-05-29 00:55:29 ERROR (MainThread) [custom_components.shinobi.api.shinobi_api] Failed to post data to ?json=true, Error: Cannot connect to host http:80 ssl:False [Try again], Line: 111
2021-05-29 00:55:29 ERROR (MainThread) [custom_components.shinobi.api.shinobi_api] Failed to login, Error: 'NoneType' object has no attribute 'get', Line: 175
2021-05-29 00:55:29 WARNING (MainThread) [custom_components.shinobi.managers.config_flow_manager] Failed to access Shinobi Video server (http://192.168.1.100)
2021-05-29 00:55:29 WARNING (MainThread) [custom_components.shinobi.config_flow] Cannot complete login`

seems it's trying to connect on port 80, but my docker is on 192.168.1.100:8180

**Comment by elad-bar** [comment]
@juan11perez according to the log and screen shot from ha forum, you have entered /admin in the path, can you pls remove it and try again?

Thanks

**Comment by elad-bar** [comment]
@juan11perez  @SHHA24  can you please post the log message?

thanks

**Comment by juan11perez** [comment]
@elad-bar 
Thank you. I did try before without the path and with the path. 
I just tried again without the path and get same error. 
This is the HA log

`2021-05-29 19:45:54 ERROR (MainThread) [custom_components.shinobi.api.shinobi_api] Failed to login, Error: API Request failed, Line: 200
2021-05-29 19:45:54 WARNING (MainThread) [custom_components.shinobi.managers.config_flow_manager] Failed to access Shinobi Video server (192.168.1.100)
2021-05-29 19:45:54 WARNING (MainThread) [custom_components.shinobi.config_flow] Cannot complete login
2021-05-29 19:47:19 ERROR (MainThread) [custom_components.shinobi.api.shinobi_api] Failed to post data to ?json=true, Error: Cannot connect to host http:80 ssl:False [Try again], Line: 111
2021-05-29 19:47:19 ERROR (MainThread) [custom_components.shinobi.api.shinobi_api] Failed to login, Error: 'NoneType' object has no attribute 'get', Line: 175`

**Comment by juan11perez** [comment]
Ok, so installed 1.0.8 and was able to complete configflow.
I now have the camera on the dashboard, but there's no preview.  if I click on the camera icon it expands and provides the video. 
In my case the lag is considerable. Over 10 secs
I configured the camera stream as mjpeg at higher fps and in the shinobi gui the lag is acceptable.
but if I leave it as mjpeg it doesnt work in HA via the integration. Only as HLS

**Comment by elad-bar** [comment]
is JPEG API enabled in Shinobi Video?

**Comment by juan11perez** [comment]
@elad-bar 
Thank you very much for your reply. JPEG API was disabled as I use an NVIDIA card and the shinobi documentation recommends turning JPEG off.

I turned it on and the preview works. In fact I also tested your deepstack-face plugin and it works really well. 

I run it in combination with tensorflow/gpu and it all works great. However, I was looking at the Shinobi setup in comparison to the "equivalent" zoneminder set up (opencv with cuda) and in my short testing Shinobi was consistently demanding on CPU.

I run unraidn on an asus MB with a ryzen 3900x and  what I noticed was that with 6 sd cameras zoneminder stays around 10 - 15% cpu load until there's an object trigger. It can then go to 70 or 80% and then back to 15%

With Shinobi on a similar set up the cpu stays at over 50% all the time. So it seems Shinobi is less efficient.

I may be using some wrong setting .

Thank you again for your response and sharing these great components.

**Comment by elad-bar** [comment]
with the new version released for HA there is no longer need to run the object detection and MQTT for motion detection as the integration is not based WebSocket directly to the Shinobi Video server.

I run 16 camera 14 of the on CPU and 2 on GPU, only face-reco (deepstack) is using the GPU,
As for the JPEG API with nVidia, I don't have an issue with that.
CPU Avg. is ~1%

I plan soon to leverge the WS integration to publish the image directly to HA instead of using the JPEG API

**Comment by juan11perez** [comment]
Thank you very much for the guidance. So you're not using object detection at all. 
Only face detection in 2 cameras. The rest is plain motion detection?

As I understand it, the benefit of object detection is to get alerts only on say person detection as opposed to any motion?

**Comment by elad-bar** [comment]
Switched all to CPU, almost no hit on CPU, face reco for all camera (16), I have also automation using NodeRED for the events

**Comment by juan11perez** [comment]
Thank you again. I'll try with face reco only.
I think it's tensorflow that hits the cpu hard as it's continously on as opposed to deepstack which is on demand.

**Comment by elad-bar** [comment]
Can we close that issue?

Thanks

**Comment by juan11perez** [comment]
Sorry, yes. Thank you. I cant close it as I didnt open it.

**Comment by ovizii** [comment]
> with the new version released for HA there is no longer need to run the object detection and MQTT for motion detection as the integration is not based WebSocket directly to the Shinobi Video server.
> 
> I run 16 camera 14 of the on CPU and 2 on GPU, only face-reco (deepstack) is using the GPU,
> As for the JPEG API with nVidia, I don't have an issue with that.
> CPU Avg. is ~1%
> 
> I plan soon to leverge the WS integration to publish the image directly to HA instead of using the JPEG API

That sounds really amazing. On a side note, would you mind sharing your camera configurations from inside shinobi? I have read countless guides and how-tos and am getting high CPU usage with only 1 camera the moment I do "anything" (like send frames or enable JPEG API) to that stream on shinobi.
