### ISSUE TITLE
Integrations should cancel non-critical tasks when receiving the stop event

### ISSUE THREAD

**Issue by chemelli74** [elad-bar/ha-shinobi#51]
Hi,

I often get the following warning during shutdown (v3.0.1/v3.0.2 of the integration, HA 2023.7.3) :

`2023-08-04 12:18:14.396 WARNING (MainThread) [homeassistant.core] Task <Task pending name='dispatcher shinobi_API_STATUS_SIGNAL' coro=<Coordinator._on_api_status_changed() running at /usr/src/homeassistant/homeassistant/util/logging.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove()]> was still running after stage 2 shutdown; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown`

Thx for investigating,

Simone

**Comment by elad-bar** [comment]
with v3.0.2 and HA v2023.8.1 i'm no longer getting that warning, pls update me after upgrade HA v2023.8.x if still happens

thanks

**Comment by elad-bar** [comment]
@chemelli74 did you manage to test it with 2023.8.x and 3.0.2 of integration?

thanks

**Comment by chemelli74** [comment]
CAM was disconnected and I'm not at home... sigh... sigh...

**Comment by elad-bar** [comment]
@chemelli74 is it still relevant?

thanks

**Comment by chemelli74** [comment]
I don't see it anymore in the log, but it's also true that the integration is not creating the CAM entity actually :-(

Simone

**Comment by chemelli74** [comment]
Really sorry, spoken too soon.
Here a message with 3.0.4:

`2023-08-31 18:48:17.799 WARNING (MainThread) [homeassistant.core] Task <Task pending name='dispatcher shinobi_API_STATUS_SIGNAL' coro=<Coordinator._on_api_status_changed() running at /usr/src/homeassistant/homeassistant/util/logging.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove()]> was still running after stage 2 shutdown; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown`

Simone

**Comment by elad-bar** [comment]
Which version of HA?

**Comment by chemelli74** [comment]
> Which version of HA?

2023.9.b1

Simone

**Comment by chemelli74** [comment]
Hi, I'm now on Home Assistant 2023.10.0b2 but this issue is unfortunately still relevant:

`2023-09-29 21:03:10.225 WARNING (MainThread) [homeassistant.core] Task <Task pending name='dispatcher shinobi_API_STATUS_SIGNAL' coro=<Coordinator._on_api_status_changed() running at /usr/src/homeassistant/homeassistant/util/logging.py:154> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove()]> was still running after stage 2 shutdown; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown`

**Comment by elad-bar** [comment]
merged your fix, thanks!!!
new release [v3.0.5](https://github.com/elad-bar/ha-shinobi/releases/tag/v3.0.5)

**Comment by chemelli74** [comment]
After a couple of week using the latest release in prod, I would say this is fixed.
