### ISSUE TITLE
Invalid server details

### ISSUE THREAD

**Issue by konvergency** [elad-bar/ha-shinobi#52]
Hello,

I can not connect to Shinobi server

I authorize API Key for 0.0.0.0 in Shinobi

In Home assistant :
I set Host as "http://192.168.xx.yy" ( with my local access )
Let default path to "/"
and port to "8080"

I try different versions of your integration V3.0.0 and the latest and always having same error
Here is the log in home assistant - it seems to be an usual error as I have seen several discussion about it in the list of issues.
I am newbie in Home assistant, and the "integration" in domoticz was working well previously for me to activate my cameras.

----
Logger: custom_components.shinobi.managers.rest_api
Source: custom_components/shinobi/managers/rest_api.py:157
Integration: Shinobi Video NVR (documentation, issues)
First occurred: 16:47:14 (12 occurrences)
Last logged: 17:09:01

Failed to post JSON to {base_url}?json=true, Error: Cannot connect to host http:80 ssl:False [Name has no usable address], Line: 233
Failed to login, Response is empty
Status changed from 'Establishing connection to API' to 'Failed to access API'

**Comment by elad-bar** [comment]
It seems that your server is inaccessible from HA, not related to the component, 
How did you install Shinobi (if docker, what source)?

**Comment by konvergency** [comment]
Thanks for your prompt reply.
Yes, it was the first thing I thought, but I do not know a simple way to test communication to shinobi without home assistant...

So for my installation, I have the ( original) old installation with shinobi on a portainer container and communication is working between domoticz and this install of shinobi ( to enable / disable camera, IP and only password are required )

Yesterday, I have done an other installation on proxmox with a container template by following this tuto https://www.youtube.com/watch?v=uQ_Egb37rmY
it is based on the ninja way recommended by shinobi ( https://docs.shinobi.video/installation/ninja-way ).

**Comment by elad-bar** [comment]
Strat with a ping, if works wget / curl to the server to see that you get the right page and not error,
Can you pls share the docker image name?
In addition, can you pls enable debug log level for component in yaml configuration then try to add integration and share the logs?

Thanks

**Comment by konvergency** [comment]
Thanks for your support.
I set debug option and I can see what does not work.
in the field host I added http so my adress became http://http://192.168...
Crazy as I thought I have tried with and without ....
Thanks again, now I can start playing !
