### ISSUE TITLE
Startup throws this - Failed to load monitor data: {'ok': False, 'msg': 'Not Authorized'}, Error: the JSON object must be str, bytes or bytearray, not NoneType, Line: 464

### ISSUE THREAD

**Issue by vw-kombi** [elad-bar/ha-shinobi#59]
Get this at every startup - but all seems fine ?

Logger: custom_components.shinobi.managers.rest_api
Source: custom_components/shinobi/managers/rest_api.py:476
Integration: Shinobi Video NVR ([documentation](https://github.com/elad-bar/ha-shinobi), [issues](https://github.com/elad-bar/ha-shinobi/issues))
First occurred: 11:19:47 (1 occurrences)
Last logged: 11:19:47

Failed to load monitor data: {'ok': False, 'msg': 'Not Authorized'}, Error: the JSON object must be str, bytes or bytearray, not NoneType, Line: 464

**Comment by chemelli74** [comment]
Hi, please share the full log with DEBUG level on.

**Comment by elad-bar** [comment]
@vw-kombi is it still relevant?

thanks

**Comment by vw-kombi** [comment]
I have removed them from ha for now.  Used the Foscam plugin to get the same info.  I did not have the time to fault find this sorry.  Will come back to it in the future.
