### ISSUE TITLE
No video in HA http 500

### ISSUE THREAD

**Issue by luzik** [elad-bar/ha-shinobi#7]
Installed, integration found my camera, all permissions added, but no video in dashboard. My browser shows error 500 in network history

http://192.168.123.10:8123/api/camera_proxy/camera.shinobi_video_tablet_kam?authSig=changed

Don't know how to trace Shinobi logs.
docker logs Shinobi looks clean

To be clear. In Shinobi interface got video streamed and recorded just fine

Does stream type matters ? Set initially to mjpeg, then changed to HLS - no change.

**Comment by luzik** [comment]
Got little more info:
Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:237 
Integration: Stream (documentation, issues) 
First occurred: 16:08:12 (10 occurrences) 
Last logged: 19:54:18

Error demuxing stream while finding first packet: [Errno 1094995529] Invalid data found when processing input: 'http://shinobi:8080/zUPdxhdzczgYJsTF8MgnIRMCbjUwS2/mjpeg/o1F4rtc13o/lZ1vDJMiA1'; last error log: [mpjpeg] Expected boundary '--' not found, instead found a line of 24 bytes
Error demuxing stream while finding first packet: [Errno 1414092869] Immediate exit requested: 'http://shinobi:8080/zUPdxhdzczgYJsTF8MgnIRMCbjUwS2/mjpeg/o1F4rtc13o/lZ1vDJMiA1'

**Comment by luzik** [comment]
Is it possible that this is related to change stream from mjpeg to HLS ?

**Comment by elad-bar** [comment]
You need to restart ha or reload the integration after updating the Shinobi Video settings,
As for why it doesn't work for you,
Please create manually camera in HA that connects to one of Shinobi Video monitors, is it working?

**Comment by luzik** [comment]
Maybe this is related to "path" settings ?
I found

```
Logger: custom_components.shinobi.camera
Source: custom_components/shinobi/camera.py:135 
Integration: Shinobi Video NVR (documentation, issues) 
First occurred: 7:13:58 (16 occurrences) 
Last logged: 7:37:07

Error getting new camera image from Shinobi Video tablet-kam: http://shinobi:8080None
Error getting new camera image from Shinobi Video tablet-kam: http://192.168.123.10:8080None
```

But when set "/" as path in integration settings - then I got:

```
Logger: custom_components.shinobi.api.shinobi_api
Source: custom_components/shinobi/api/shinobi_api.py:125 
Integration: Shinobi Video NVR (documentation, issues) 
First occurred: 7:17:25 (30 occurrences) 
Last logged: 7:35:32

Failed to post data to ?json=true, Error: 404, message='Not Found', url=URL('http://shinobi:8080//?json=true'), Line: 115
Failed to post data to ?json=true, Error: 404, message='Not Found', url=URL('http://192.168.123.10:8080//?json=true'), Line: 115
Failed to post data to ?json=true, Error: Cannot connect to host http:80 ssl:False [Try again], Line: 112

Failed to get permanent API Key, please go to Shinobi Video Dashboard and add API for `luzik@gda.pl`

Failed to access Shinobi Video server (shinobi)
Failed to access Shinobi Video server (192.168.123.10)
Failed to access Shinobi Video server (http://shinobi)
```

**Comment by elad-bar** [comment]
It seems like you created integration to 2 servers, one by hostname the other using ip, can you pls explain? 

Thanks

**Comment by luzik** [comment]
Yeah, I've tried both hostnames to work, but no one did

**Comment by elad-bar** [comment]
Can you please post the logs as debug from the log file not ui, without that i cannot assist

Thanks

**Comment by luzik** [comment]
What value "path" param should have if I can access it on http://shinobi:8080 ?

**Comment by elad-bar** [comment]
You should leave it empty, without logs in debug level I cannot assist

**Comment by arag00rn** [comment]
@luzik I had same issue. Please be sure to enable JPEG API on Shinobi camera's settings.

It was written in requirements, I didn't notice immediately.

Hope this help you as well.

**Comment by luzik** [comment]
Agh - that was it! Thx!
Message with url http://shinobi:8080None was false lead. Please consider swapping None with ''
Also please consider hide video window when JPEG API is not available, and add some warning messages about this to HA

**Comment by elad-bar** [comment]
Will add dedicated error message including check for all monitors support JPEG API
