### ISSUE TITLE
Error adding entity camera with HA 2024.11.0

### ISSUE THREAD

**Issue by chemelli74** [elad-bar/ha-shinobi#75]
After the upgrade, camera entity is no longer created:

`2024-11-07 18:06:45.407 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'shinobi' uses 'async_config_entry_first_refresh', which is only supported when entry state is ConfigEntryState.SETUP_IN_PROGRESS, but it is in state ConfigEntryState.LOADED, This will stop working in Home Assistant 2025.11 at custom_components/shinobi/managers/coordinator.py, line 204: await self.async_config_entry_first_refresh(), please create a bug report at https://github.com/elad-bar/ha-shinobi/issues`

`2024-11-07 18:06:45.495 ERROR (MainThread) [homeassistant.components.camera] Error adding entity camera.shinobi_video_terrazzo for domain camera with platform shinobi`

**Comment by isdedina** [comment]
The same here, Shinobi integration is not working after upgrade to HA 2024.11.0.

**Comment by deployor** [comment]
I have the same problem here, all my cameras are broken after the 24.11 😢.

**Comment by elad-bar** [comment]
sorry for the late response, i was on 3 weeks vacation abroad, will release fix for it soon

**Comment by elad-bar** [comment]
pls check [v3.0.13](https://github.com/elad-bar/ha-shinobi/releases/tag/v3.0.13)

thanks

**Comment by isdedina** [comment]
Hello, thank you, now the integration is working in 2024.11, but it is worse than in HA 2024.10. The cameras stream setup takes long and sometiems live mode is not working.

**Comment by elad-bar** [comment]
if the issue was solved I will close it, if the issue for 2024.10 is relevant, I will add a restriction that next version applicable only for grather than 2024.11 but cannot do it for the current version

@chemelli74 can you pls update whether it is solved for you?

thanks

**Comment by isdedina** [comment]
Hello, for me it is solved. Thank you.
