### ISSUE TITLE
Home Assistant: Motion Detection Issue

### ISSUE THREAD

**Issue by 4dsistemi** [elad-bar/ha-shinobi#77]
It seems that Home Assistant detects motion for the first one or two events but then stops triggering afterward.

**HA Version:**
Core
2024.11.3
Supervisor
2024.11.4
Operating System
13.2
Frontend
20241106.2

**ha-shinobi:**
3.0.13

**Comment by elad-bar** [comment]
Please share debug log level that explains the scenario you experienced 
Thanks

**Comment by 4dsistemi** [comment]
There's nothing in mia registry.

This is my diagnostic details:

[config_entry-shinobi-01JE4WT2C8BQ1RZC74T94XNN17.json](https://github.com/user-attachments/files/18009602/config_entry-shinobi-01JE4WT2C8BQ1RZC74T94XNN17.json)

**Comment by elad-bar** [comment]
Diagnostic file provides snapshot, I will need the logs in debug level to devug the issue

**Comment by elad-bar** [comment]
nvm, found the issue fixed it, will soon share new release, thanks for reporting

**Comment by elad-bar** [comment]
@4dsistemi pls check and update if it solved the issue gor you

Thanks

**Comment by 4dsistemi** [comment]
Thank you for your assistance. The issue is now resolved.
