### ISSUE TITLE
Any recommended settings for JPEG API?

### ISSUE THREAD

**Issue by ovizii** [elad-bar/ha-shinobi#8]
This seems to be default, should I change anything?

![image](https://user-images.githubusercontent.com/837902/120890536-a0359600-c603-11eb-9658-add16ac89b32.png)

**Comment by elad-bar** [comment]
you should leave it like that, JPEG API is being used for the still (preview) image of the camera,
Stream section is defining how you will get the video stream

**Comment by ovizii** [comment]
I switched to your extension since the other one was archived: https://github.com/xannor/ha_shinobicctv 

Is there no other way? if I switch on the JPEG API, the machine running shinobi jumps to 20-30 % CPU usage. 

The other extension was working without the JPEG API and was still showing stills previews :-(

**Comment by elad-bar** [comment]
The other one extracted the images from the stream, 20-30% of Shinobi or HA?
What happens if HA component is not installed an Shinobi JPEG API is on? trying to isolate the issue

Thanks

**Comment by ovizii** [comment]
There's no relation to your addon as the CPU spike happens after adding jpeg api to shinobi, before even connecting it to HA:

20-30 % of Shinobi. Shinobi runs as a docker container on the same host which runs HA inside a VM. 

I guess I'll do without this still preview then.

**Comment by elad-bar** [comment]
I will try removing the dependency on JPEG API next weekend

**Comment by elad-bar** [comment]
In the old component it extracted it from the video stream, I checked it and it increase the bandwidth consumption as well as CPU usage compared to JPEG API, will try to extract it from websocket, otherwise it will not be efficient.

**Comment by ovizii** [comment]
I saw your latest changelog:

`JPEG API is not enabled for {camera.name}, Camera will not be created` 

I was just wondering i this is necessary? Until now, the camera could be added without the JPEG API, one could just not see stills but one could use the live view. 

Jut a thought from my side, no need to reply or do anything. I'm mostly just using HA + ffpmpeg_noise to trigger shinobi recording when noise is detected, not really having a need to add my cameras to HA anymore.

**Comment by elad-bar** [comment]
tried it, it consumes more resources as the HA opens 2 streams, one for the video and one for extracting the image.

you can get to the same result by defining the audio sensor within Shinobi, by triggering the audio detector run any automation, can it work for you?

thanks

**Comment by ovizii** [comment]
> you can get to the same result by defining the audio sensor within Shinobi, by triggering the audio detector run any automation, can it work for you?
> 
> thanks

Yes, when I started using HA and ffmpeg_noise I wasn't aware shinobi can do that on its own and even send notifications so I will probably shift that from HA to shinobi.

Thanks for the pointer!
