### ISSUE TITLE
"Path" setup field, not defined in readme, required?

### ISSUE THREAD

**Issue by moorsey** [elad-bar/ha-shinobi#9]
Trying to add my Shinobi server, sat behind nginx proxy, so adding as follows:

Host: https://shinobi.example.com
Path: ?? Left blank
Port: 443
Username: admin@admin.com
Password: ***

But am getting "Invalid server details" error

Also a tad confused on the API key, I have generated one, but there doesn't appear to be anywhere to put it, instructions mention generating one, but not anything after that?  Maybe that is as expected

Checked the logs, but nothing being entered when Home Assistant attempts a connection

**Comment by elad-bar** [comment]
API key is being extracted automatically based on the credentials, can you please post debug level logs?

Thanks

**Comment by elad-bar** [comment]
@moorsey ?

**Comment by moorsey** [comment]
My apologies, I have been locked out of the admin page, so can't access any logging etc

Best close this for now, will re-open when I have sorted this out and if still an issue, looks like I will need to reinstall
